name: CI
on: [push, pull_request]
jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'sbt/sbt-jni'
    name: ${{ matrix.os }} tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt test-plugin
